import os
from playwright.sync_api import Page, expect
from pages.login_page import LoginPage
from pages.spravne_konanie_page import SpravneKonanie
from utils.helpers import Helper as helper

username_riad = os.getenv("EPRIHLASKY_RIADITEL_USERNAME")
password_riad = os.getenv("EPRIHLASKY_RIADITEL_PASSWORD")


def test_spravne_konanie_SS(page: Page) -> None:
    login = LoginPage(page)
    sk = SpravneKonanie(page)
    
    login.login_as_riaditel(username_riad, password_riad, "910021624")
    sk.navigate_to_spravne_konanie()
    sk.search("benko")
    sk.click_spatvzatie_konania()
    sk.select_ucastnik("benko erik", "Benko Erik")
    sk.upload_dokument()
    sk.click_pokracovat()
    expect(page.locator("#doplnenie-udajov-description")).to_contain_text("Vyplňte všetky potrebné náležitosti rozhodnutia o zastavení konania.")
    expect(page.locator("#doplnenie-udajov")).to_contain_text("Doplnenie údajov")
    sk.click_prejst_na_podpis()
    expect(page.locator("#podpis-rozhodnuti")).to_contain_text("Generovanie rozhodnutí")
    expect(page.locator("#podpis-rozhodnuti")).to_contain_text("Skontrolujte všetky rozhodnutia a pristúpte ku generovaniu.")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Stredná škola pre AT")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("R-26-910021624-00009")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("11.08.2026")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("ROZHODNUTIE")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Stredná škola pre AT ako príslušný správny orgán podľa § 37 ods. 1 písm. a) zákona č. 321/2025 Z. z. o školskej správe a o zmene a doplnení niektorých zákonov v spojení s § 30 ods. 1 písm. d) Správneho poriadku rozhodla takto:")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("zastavuje konanie")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("vo veci prihlášky účastníka konania Erik Benko, nar. 22.01.2010, trvale bytom Juríčková 896/2, 03657, Košariská na vzdelávanie v Stredná škola pre AT, ktorú podal Tomáš Lukáč, Ražná 58/232, 01508, Košariská dňa 22.04.2026")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Odôvodnenie:")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Zastavenie konania.")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Poučenie:")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Proti tomuto rozhodnutiu možno podať podľa § 53 a 54 Správneho poriadku odvolanie do 15 dní odo dňa jeho doručenia, a to na Stredná škola pre AT. Toto rozhodnutie je preskúmateľné súdom podľa Správneho súdneho poriadku po vyčerpaní riadnych opravných prostriedkov.")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Peter Fodrok")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("riaditeľ")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Rozhodnutie sa doručuje:")
    expect(page.locator("#aktualny-nahlad-container")).to_contain_text("Tomáš Lukáč, Ražná 58/232, 01508, Košariská")
    sk.click_vygenerovat()
    expect(page.locator("#podpis-success-title")).to_contain_text("Generovanie 1 rozhodnutia bolo spustené.")
    expect(page.locator("#podpis-success-desc")).to_contain_text("Tento proces môže v závislosti od počtu vybraných rozhodnutí trvať niekoľko minút až hodín.")
    sk.click_spat_na_spravne_konanie()
    sk.cakaj_na_stav("benko", "Rozhodnutie o zastavení konania pripravené na odoslanie.")
    sk.click_vybrat_first()
    sk.click_odoslat_rozhodnutie_zastavenia()
    expect(page.locator("h1")).to_contain_text("Zastavenie konania – Späťvzatie podania")
    expect(page.get_by_role("paragraph")).to_contain_text("Skontrolujte rozhodnutie. Po skontrolovaní odošlite rozhodnutie elektronicky kliknutím na \"Odoslať do e-desk Zákonného zástupcu\". V prípade, že nie je možné zaslať rozhodnutie o odvolaní elektronicky môžete rozhodnutie \"Označiť ako odoslané\", a rozhodnutie odoslať poštou.")
    expect(page.locator("#warning-container")).to_contain_text("Rozhodnutie o odvolaní nie je možné zaslať zákonnému zástupcovi elektronicky. Stiahnite si dokument vo formáte PDF, označte ho ako \"zaslané ZZ\" a pošlite ho poštou.")
    expect(page.locator("#pdfFrame")).to_be_visible()
    expect(page.get_by_role("button", name="Označiť ako odoslané")).to_be_visible()
    sk.click_oznacit_ako_odoslane()
    page.wait_for_timeout(2000)
    sk.search("benko")
    expect(page.locator("#sub-riaditel-spravne-konanie")).to_contain_text("Rozhodnutie o zastavení konania odoslané.")
    sk.click_spatvzatie_konania()
    page.wait_for_timeout(2000)
    sk.select_ucastnik("benko erik", "Benko Erik")
    sk.upload_dokument()
    sk.click_pokracovat()
    sk.click_prejst_na_podpis()
    sk.click_vygenerovat()
    expect(page.locator("#podpis-success-title")).to_contain_text("Generovanie 1 rozhodnutia bolo spustené.")
    expect(page.locator("#podpis-success-desc")).to_contain_text("Tento proces môže v závislosti od počtu vybraných rozhodnutí trvať niekoľko minút až hodín.")
    sk.click_spat_na_spravne_konanie()
    
